#!/bin/sh
url="$1"
curl -s --request POST \
  --url 'https://www.googleapis.com/urlshortener/v1/url?key=AIzaSyDmLV903c_BpxvSahVeBWUmEn8NigKoX2Q' \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --data "{\"longUrl\": \"${url}\"}" | jq -r '.id'